package com.ravunana.manda.domain.enumeration;

/**
 * The EntidadeSistema enumeration.
 */
public enum EntidadeSistema {
    SOFTWARE, LICENCA_SOFTWARE, LOOKUP, LOOKUP_ITEM, FLUXO_DOCUMENTO, DOCUMENTO_COMERCIAL, IMPOSTO, MORADA_PESSOA, CONTACTO_PESSOA, LOCALIZACAO_EMPRESA, CONTACTO_EMPRESA, EMPRESA, PESSOA, CLIENTE, FORNECEDOR, RELACIONAMENTO_PESSOA, COORDENADA_BANCARIA, ARQUIVO, UNIDADE_MEDIDA, CLASSE_CONTA, CONTA, ESCRITURACAO_CONTABIL, REGRA_MOVIMENTACAO_CREDITO, REGRA_MOVIMENTACAO_DEBITO, CONTA_DEBITO, CONTA_CREDITO, MOEDA, FORMA_LIQUIDACAO, LANCAMENTO_FINANCEIRO, DETALHE_LANCAMENTO, RETENCAO_FONTE, LOCAL_ARMAZENAMENTO, COMPOSTO_PRODUTO, FAMILIA_PRODUTO, PRODUTO, CONVERSAO_UNIDADE, COMPRA, ITEM_COMPRA, DEVOLUCAO_COMPRA, VENDA, ITEM_VENDA, DEVOLUCAO_VENDA, AUDITORIA_DOCUMENTO_COMERCIAL
}
